version: "3.3"
services:
  db-tests:
    container_name: db-tests
    build:
      context: .
      dockerfile: ./tests/db-test-dockerfile
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=changeit
      - POSTGRES_DB=db
    ports:
      - 5432:5432